'use client';

import { useState, useEffect, useRef } from 'react';
import { motion, useInView, AnimatePresence } from 'framer-motion';
import {
  FiServer, FiCpu, FiActivity, FiShield, FiDatabase,
  FiArrowRight, FiClock, FiRefreshCw, FiZap, FiInfo,
  FiExternalLink, FiChevronRight, FiChevronDown, FiSearch,
  FiCheck, FiAlertCircle, FiBarChart2, FiTrendingUp, FiTarget,
  FiRadio, FiWifi, FiUsers, FiLayers, FiBox,
  FiGitBranch, FiGrid, FiMessageCircle, FiSend,
  FiPlay, FiPause, FiCode, FiTool, FiSettings, FiHash,
  FiHardDrive, FiMonitor, FiAlertTriangle, FiLock,
  FiDollarSign, FiCrosshair, FiPieChart, FiNavigation,
} from 'react-icons/fi';

function AnimatedCounter({ value, suffix = '', duration = 2 }: { value: number; suffix?: string; duration?: number }) {
  const [count, setCount] = useState(0);
  const ref = useRef(null);
  const isInView = useInView(ref, { once: true, margin: '-50px' });

  useEffect(() => {
    if (!isInView) return;
    let start = 0;
    const increment = value / (duration * 60);
    const timer = setInterval(() => {
      start += increment;
      if (start >= value) {
        setCount(value);
        clearInterval(timer);
      } else {
        setCount(Math.floor(start));
      }
    }, 1000 / 60);
    return () => clearInterval(timer);
  }, [isInView, value, duration]);

  return (
    <span ref={ref}>
      {count.toLocaleString()}{suffix}
    </span>
  );
}

const fadeUp = {
  hidden: { opacity: 0, y: 40 },
  visible: { opacity: 1, y: 0, transition: { duration: 0.6 } },
};

const stagger = {
  hidden: {},
  visible: { transition: { staggerChildren: 0.1 } },
};

const cardHover = {
  rest: { scale: 1, boxShadow: '0 1px 3px rgba(0,0,0,0.05)' },
  hover: { scale: 1.02, boxShadow: '0 10px 40px rgba(37,99,235,0.15)' },
};

export default function VegaPage() {
  const [expandedComponent, setExpandedComponent] = useState<string | null>(null);
  const [aiView, setAiView] = useState<string | null>(null);

  const orderLifecycle = [
    { label: 'Strategy Signal', desc: 'Signal generated by Kuber Alpha / strategy engine', icon: FiTarget },
    { label: 'TalkStrategy API', desc: 'Receives order request via REST/WebSocket', icon: FiCode },
    { label: 'TalkStrategy App', desc: 'Middleware: validates, enriches, and queues orders', icon: FiServer },
    { label: 'Order Processor', desc: 'Executes risk checks, margin validation, broker routing', icon: FiCpu },
    { label: 'Broker Integration', desc: 'Formats and sends order to broker (XTS/Greeksoft)', icon: FiNavigation },
    { label: 'Broker API', desc: 'Broker receives and acknowledges the order', icon: FiWifi },
    { label: 'Exchange', desc: 'Order placed on NSE/BSE/MCX exchange', icon: FiRadio },
    { label: 'Trade Confirmation', desc: 'Fill confirmation flows back through the pipeline', icon: FiCheck },
    { label: 'Back to API', desc: 'Status and position updates sent to TalkStrategy API', icon: FiRefreshCw },
  ];

  const responsibilities = [
    'Order Validation',
    'Risk Validation',
    'Margin Check',
    'Broker Routing',
    'Execution',
    'Status Tracking',
    'Position Update',
    'Logs',
    'Analytics',
    'Kill Switch Layer 3 (1.50%)',
  ];

  const components = [
    { name: 'TalkStrategy API', desc: 'RESTful API that receives strategy signals and order requests from upstream engines. Validates input format and forwards to the TalkStrategy middleware app.' },
    { name: 'TalkStrategy App', desc: 'Middleware application that performs business logic validation, enriches order payloads with account/strategy context, and queues orders for the order processor.' },
    { name: 'Order Processor', desc: 'Core execution engine that performs pre-trade risk checks, margin validation, broker selection, and manages the order state machine through its complete lifecycle.' },
    { name: 'Broker Integration', desc: 'XTS and Greeksoft broker connectors. Formats orders into broker-specific protocols, maintains session state, and handles credential management and reconnection.' },
    { name: 'Fund Allocator', desc: 'Manages fund allocation and position sizing across multiple strategies and accounts, ensuring compliance with configured allocation rules.' },
    { name: 'FIX Engine', desc: 'FIX protocol engine for standardized order routing. Supports FIX 4.4 with custom tag extensions for Indian market requirements.' },
  ];

  const dependencies = [
    { name: 'TalkStrategy API', role: 'Entry Point' },
    { name: 'TalkStrategy App', role: 'Middleware' },
    { name: 'Order Processor', role: 'Core Engine' },
    { name: 'Broker Integration', role: 'Connector' },
    { name: 'Broker APIs', role: 'External' },
    { name: 'Exchange', role: 'Destination' },
  ];

  const healthItems = [
    { label: 'Engine', status: 'Healthy', color: 'bg-green-500' },
    { label: 'API', status: 'Operational', color: 'bg-green-500' },
    { label: 'Broker 1 (XTS)', status: 'Connected', color: 'bg-green-500' },
    { label: 'Broker 2 (Greeksoft)', status: 'Connected', color: 'bg-green-500' },
    { label: 'Order Queue', status: 'Normal', color: 'bg-green-500' },
    { label: 'Database', status: 'Connected', color: 'bg-green-500' },
    { label: 'CPU', status: '34%', color: 'bg-green-500' },
    { label: 'Memory', status: '51%', color: 'bg-green-500' },
    { label: 'Kill Switch', status: 'Armed', color: 'bg-amber-500' },
    { label: 'FIX Engine', status: 'Standby', color: 'bg-amber-500' },
  ];

  const overviewCards = [
    { title: 'Purpose', icon: FiTarget, content: 'Vega is the enterprise order execution engine that bridges strategy signals with broker APIs. It processes order requests from Kuber Alpha and TalkStrategy API, validates them through risk and margin checks, and routes them to connected brokers for exchange execution.' },
    { title: 'Business Importance', icon: FiTrendingUp, content: 'Vega is the final gateway between strategy decisions and market execution. Every rupee traded flows through Vega. Its reliability directly impacts P&L — downtime means missed opportunities and unmanaged risk during volatile markets.' },
    { title: '4 Components', icon: FiGrid, content: 'TalkStrategy API (RESTful entry point), TalkStrategy App (middleware validation & enrichment), Order Processor (execution state machine), Broker Integration (XTS & Greeksoft connectors with credential management).' },
    { title: 'Connected Engines', icon: FiGitBranch, content: 'Kuber Alpha (signal source), Kavach (risk management), Rakshak (system protection), TalkDelta (position tracking), Chitragupta (audit logging), ODIN (alternative execution path).' },
    { title: 'Input Sources', icon: FiArrowRight, content: 'Kuber Alpha strategy signals, TalkStrategy API direct orders, Surya configurations, External strategy engines, Manual override requests.' },
    { title: 'Output Destinations', icon: FiSend, content: 'Broker APIs (XTS, Greeksoft), Exchange (via broker), TalkDelta (position updates), Chitragupta (audit trail), Kavach (risk updates), Rakshak (health telemetry).' },
    { title: 'Brokers Supported', icon: FiWifi, content: 'XTS (primary — equities, derivatives), Greeksoft (secondary — commodities, currency), FIX (standardized protocol for institutional clients). Extensible architecture for adding new brokers.' },
    { title: 'Latency', icon: FiClock, content: '8ms average end-to-end from API receipt to broker acknowledgment. Order validation under 2ms. Broker dispatch under 3ms. P99 latency under 15ms during peak load.' },
    { title: 'Throughput', icon: FiZap, content: '500 orders per second sustained. Burst capacity up to 1,200 orders/sec during market open auction. Queue depth monitoring with automatic throttling at 80% capacity.',
    },
  ];

  const aiExplanations: Record<string, string> = {
    simple: 'Vega is like the checkout counter of the trading platform. When a trading strategy decides to buy or sell, it sends that request to Vega. Vega then checks: "Do we have enough money?", "Is this too risky?", and "Which broker should we use?" If everything passes, Vega sends the order to the exchange through the broker, tracks it until it completes, and updates everyone on the result — all in under 8 milliseconds.',
    technical: 'Vega implements a multi-component execution pipeline: TalkStrategy API (REST/WS entry) → TalkStrategy App (middleware with order enrichment and queue management) → Order Processor (state machine with pre-trade risk, margin validation, broker selection) → Broker Integration (XTS and Greeksoft connectors with FIX 4.4 support). Features include position-aware sizing, kill switch at Layer 3 (1.50% drawdown trigger), automatic broker failover, and comprehensive audit logging to Chitragupta.',
    architecture: 'Vega sits at Layer 4 (Execution Layer) in the ecosystem: Strategy Factory → Kuber Alpha → TalkStrategy API → Vega (Order Execution) → Broker APIs → Exchange. Internally, it uses a pipeline architecture: API Gateway → Middleware → Order Processor → Broker Adapter. The Kill Switch layer operates independently at 1.50% drawdown — if this threshold is breached, Vega suspends all new orders while allowing position exits. All executions are logged to Chitragupta for regulatory compliance.',
  };

  return (
    <div className="min-h-screen bg-white">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8 space-y-16">

        {/* SECTION 1: Hero Header */}
        <motion.section
          initial="hidden"
          animate="visible"
          variants={fadeUp}
          className="pt-8 pb-4"
        >
          <div className="flex items-center gap-4 mb-4">
            <div className="w-14 h-14 rounded-2xl bg-red-100 flex items-center justify-center">
              <FiCrosshair className="text-2xl text-red-600" />
            </div>
            <div>
              <h1 className="text-4xl md:text-5xl font-bold text-gray-900">Vega Engine</h1>
              <p className="text-lg text-gray-500 mt-1">Enterprise Order Execution & Strategy API Platform</p>
            </div>
          </div>
          <p className="text-xl text-gray-600 font-medium mb-2">Order Execution. Broker Integration. Real-Time Low Latency.</p>
          <p className="text-gray-500 max-w-3xl mb-6 leading-relaxed">
            Vega is the execution backbone of the Algo IQ ecosystem, processing hundreds of orders per second
            with sub-10ms latency. It connects strategy signals to broker APIs through a robust pipeline
            spanning four integrated components.
          </p>
          <div className="flex flex-wrap gap-3">
            <span className="inline-flex items-center gap-2 px-4 py-2 bg-red-50 text-red-700 rounded-full text-sm font-semibold">
              <FiHash /> v3.4.0
            </span>
            <span className="inline-flex items-center gap-2 px-4 py-2 bg-green-50 text-green-700 rounded-full text-sm font-semibold">
              <span className="w-2 h-2 rounded-full bg-green-500 animate-pulse" /> Production
            </span>
            <span className="inline-flex items-center gap-2 px-4 py-2 bg-amber-50 text-amber-700 rounded-full text-sm font-semibold">
              <FiZap /> 500 orders/sec
            </span>
            <span className="inline-flex items-center gap-2 px-4 py-2 bg-purple-50 text-purple-700 rounded-full text-sm font-semibold">
              <FiGrid /> 4 Components
            </span>
          </div>
        </motion.section>

        {/* SECTION 2: Ecosystem Position Diagram */}
        <motion.section
          initial="hidden"
          whileInView="visible"
          viewport={{ once: true, margin: '-100px' }}
          variants={fadeUp}
          className="bg-[#F8FAFC] rounded-2xl p-6 md:p-8"
        >
          <h2 className="text-2xl font-bold text-gray-900 mb-6 flex items-center gap-3">
            <FiGitBranch className="text-[#2563EB]" /> Ecosystem Position — Execution Flow
          </h2>
          <div className="overflow-x-auto">
            <svg viewBox="0 0 950 160" className="w-full max-w-4xl mx-auto" style={{ minWidth: '750px' }}>
              <defs>
                <filter id="glow-vega">
                  <feGaussianBlur stdDeviation="4" result="blur" />
                  <feMerge><feMergeNode in="blur" /><feMergeNode in="SourceGraphic" /></feMerge>
                </filter>
              </defs>
              {/* Kuber Alpha */}
              <rect x="10" y="55" width="120" height="50" rx="12" fill="#F3E8FF" stroke="#9333EA" strokeWidth="1.5" />
              <text x="70" y="85" textAnchor="middle" fill="#581C87" fontSize="13" fontWeight="600" fontFamily="system-ui">Kuber Alpha</text>
              <line x1="130" y1="80" x2="175" y2="80" stroke="#94A3B8" strokeWidth="2" markerEnd="url(#arrowGrayV)" />
              {/* TalkStrategy API */}
              <rect x="180" y="55" width="130" height="50" rx="12" fill="#EFF6FF" stroke="#2563EB" strokeWidth="1.5" />
              <text x="245" y="85" textAnchor="middle" fill="#1E3A5F" fontSize="12" fontWeight="600" fontFamily="system-ui">TalkStrategy API</text>
              <line x1="310" y1="80" x2="355" y2="80" stroke="#94A3B8" strokeWidth="2" markerEnd="url(#arrowGrayV)" />
              {/* TalkStrategy App */}
              <rect x="360" y="55" width="130" height="50" rx="12" fill="#EFF6FF" stroke="#2563EB" strokeWidth="1.5" />
              <text x="425" y="85" textAnchor="middle" fill="#1E3A5F" fontSize="12" fontWeight="600" fontFamily="system-ui">TS App</text>
              <line x1="490" y1="80" x2="535" y2="80" stroke="#94A3B8" strokeWidth="2" markerEnd="url(#arrowGrayV)" />
              {/* Vega - Glowing */}
              <motion.rect
                x="540" y="50" width="120" height="60" rx="14"
                fill="#DC2626" filter="url(#glow-vega)"
                animate={{ opacity: [1, 0.85, 1] }}
                transition={{ duration: 2, repeat: Infinity, ease: 'easeInOut' }}
              />
              <text x="600" y="85" textAnchor="middle" fill="#FFFFFF" fontSize="15" fontWeight="700" fontFamily="system-ui">Vega</text>
              <line x1="660" y1="80" x2="705" y2="80" stroke="#94A3B8" strokeWidth="2" markerEnd="url(#arrowGrayV)" />
              {/* Broker */}
              <rect x="710" y="55" width="110" height="50" rx="12" fill="#FFF7ED" stroke="#EA580C" strokeWidth="1.5" />
              <text x="765" y="85" textAnchor="middle" fill="#9A3412" fontSize="13" fontWeight="600" fontFamily="system-ui">Broker API</text>
              <line x1="820" y1="80" x2="860" y2="80" stroke="#94A3B8" strokeWidth="2" markerEnd="url(#arrowGrayV)" />
              {/* Exchange */}
              <rect x="850" y="55" width="90" height="50" rx="12" fill="#F0FDF4" stroke="#16A34A" strokeWidth="1.5" />
              <text x="895" y="85" textAnchor="middle" fill="#166534" fontSize="14" fontWeight="600" fontFamily="system-ui">Exchange</text>

              {/* Pulse on Vega */}
              <motion.circle
                cx="600" cy="75" r="10" fill="none" stroke="#F59E0B" strokeWidth="3"
                initial={{ r: 5, opacity: 1 }}
                animate={{ r: 40, opacity: 0 }}
                transition={{ duration: 2, repeat: Infinity, ease: [0.25, 0.1, 0.25, 1] }}
              />

              <defs>
                <marker id="arrowGrayV" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6" markerHeight="6" orient="auto">
                  <path d="M 0 0 L 10 5 L 0 10 z" fill="#94A3B8" />
                </marker>
              </defs>
            </svg>
          </div>
        </motion.section>

        {/* SECTION 3: Interactive Overview Cards */}
        <motion.section
          initial="hidden"
          whileInView="visible"
          viewport={{ once: true, margin: '-100px' }}
          variants={stagger}
        >
          <h2 className="text-2xl font-bold text-gray-900 mb-6 flex items-center gap-3">
            <FiLayers className="text-[#2563EB]" /> Overview
          </h2>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            {overviewCards.map((card) => (
              <motion.div
                key={card.title}
                initial="rest"
                whileHover="hover"
                variants={cardHover}
                className="bg-[#F8FAFC] border border-gray-200 rounded-2xl p-5 cursor-default transition-colors hover:border-[#2563EB]/30"
              >
                <div className="flex items-center gap-3 mb-3">
                  <div className="w-10 h-10 rounded-xl bg-blue-100 flex items-center justify-center flex-shrink-0">
                    <card.icon className="text-[#2563EB]" />
                  </div>
                  <h3 className="font-semibold text-gray-900">{card.title}</h3>
                </div>
                <p className="text-sm text-gray-600 leading-relaxed">{card.content}</p>
              </motion.div>
            ))}
          </div>
        </motion.section>

        {/* SECTION 4: Order Lifecycle Animation */}
        <motion.section
          initial="hidden"
          whileInView="visible"
          viewport={{ once: true, margin: '-100px' }}
          variants={fadeUp}
          className="bg-[#F8FAFC] rounded-2xl p-6 md:p-8"
        >
          <h2 className="text-2xl font-bold text-gray-900 mb-8 flex items-center gap-3">
            <FiRefreshCw className="text-[#2563EB]" /> Order Lifecycle
          </h2>
          <div className="relative">
            <div className="absolute left-6 top-0 bottom-0 w-0.5 bg-[#2563EB]/20 hidden md:block" />
            <div className="space-y-6">
              {orderLifecycle.map((step, i) => (
                <motion.div
                  key={step.label}
                  initial={{ opacity: 0, x: -30 }}
                  whileInView={{ opacity: 1, x: 0 }}
                  viewport={{ once: true }}
                  transition={{ duration: 0.5, delay: i * 0.1 }}
                  className="flex items-start gap-4 md:gap-6 relative"
                >
                  <div className={`w-12 h-12 rounded-full flex items-center justify-center flex-shrink-0 z-10 border-2 ${i === 0 ? 'bg-purple-50 border-purple-400 text-purple-600' : i >= 3 && i <= 5 ? 'bg-[#2563EB] border-[#2563EB] text-white' : i === orderLifecycle.length - 1 ? 'bg-green-50 border-green-400 text-green-600' : 'bg-white border-[#2563EB]/40 text-[#2563EB]'}`}>
                    <step.icon />
                  </div>
                  <div className="bg-white border border-gray-200 rounded-2xl p-4 flex-1 shadow-sm">
                    <h4 className="font-semibold text-gray-900">{step.label}</h4>
                    <p className="text-sm text-gray-500 mt-1">{step.desc}</p>
                  </div>
                </motion.div>
              ))}
            </div>
          </div>
        </motion.section>

        {/* SECTION 5: Internal Architecture SVG */}
        <motion.section
          initial="hidden"
          whileInView="visible"
          viewport={{ once: true, margin: '-100px' }}
          variants={fadeUp}
        >
          <h2 className="text-2xl font-bold text-gray-900 mb-6 flex items-center gap-3">
            <FiBox className="text-[#2563EB]" /> Internal Architecture — 4 Components
          </h2>
          <div className="bg-[#F8FAFC] rounded-2xl p-6 md:p-8 overflow-x-auto">
            <svg viewBox="0 0 900 220" className="w-full max-w-4xl mx-auto" style={{ minWidth: '700px' }}>
              {[
                { x: 20, y: 30, w: 180, h: 60, label: '1. TalkStrategy API', subtitle: 'RESTful Entry Point', color: '#2563EB' },
                { x: 240, y: 30, w: 180, h: 60, label: '2. TalkStrategy App', subtitle: 'Middleware / Validator', color: '#7C3AED' },
                { x: 460, y: 30, w: 180, h: 60, label: '3. Order Processor', subtitle: 'Execution State Machine', color: '#EA580C' },
                { x: 680, y: 30, w: 190, h: 60, label: '4. Broker Integration', subtitle: 'XTS / Greeksoft / FIX', color: '#DC2626' },
              ].map((block, i) => (
                <g key={block.label} className="cursor-pointer" onClick={() => alert(`${block.label}: ${block.subtitle}. Part of the Vega 4-component execution pipeline.`)}>
                  <rect x={block.x} y={block.y} width={block.w} height={block.h} rx="14" fill={block.color + '10'} stroke={block.color} strokeWidth="2" />
                  <text x={block.x + block.w / 2} y={block.y + block.h / 2 - 6} textAnchor="middle" fill={block.color} fontSize="13" fontWeight="700" fontFamily="system-ui">{block.label}</text>
                  <text x={block.x + block.w / 2} y={block.y + block.h / 2 + 14} textAnchor="middle" fill="#64748B" fontSize="11" fontFamily="system-ui">{block.subtitle}</text>
                </g>
              ))}
              {/* Arrows between components */}
              <line x1="200" y1="60" x2="240" y2="60" stroke="#CBD5E1" strokeWidth="2" markerEnd="url(#arrowSlateV)" />
              <line x1="420" y1="60" x2="460" y2="60" stroke="#CBD5E1" strokeWidth="2" markerEnd="url(#arrowSlateV)" />
              <line x1="640" y1="60" x2="680" y2="60" stroke="#CBD5E1" strokeWidth="2" markerEnd="url(#arrowSlateV)" />

              {/* Layer labels */}
              <text x="110" y="120" textAnchor="middle" fill="#64748B" fontSize="11" fontFamily="system-ui">Entry</text>
              <text x="330" y="120" textAnchor="middle" fill="#64748B" fontSize="11" fontFamily="system-ui">Validation</text>
              <text x="550" y="120" textAnchor="middle" fill="#64748B" fontSize="11" fontFamily="system-ui">Execution</text>
              <text x="775" y="120" textAnchor="middle" fill="#64748B" fontSize="11" fontFamily="system-ui">Connectivity</text>

              <defs>
                <marker id="arrowSlateV" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6" markerHeight="6" orient="auto">
                  <path d="M 0 0 L 10 5 L 0 10 z" fill="#CBD5E1" />
                </marker>
              </defs>
            </svg>
            <p className="text-center text-sm text-gray-400 mt-4">Click any component block to view details</p>
          </div>
        </motion.section>

        {/* SECTION 6: Responsibilities Dashboard */}
        <motion.section
          initial="hidden"
          whileInView="visible"
          viewport={{ once: true, margin: '-100px' }}
          variants={stagger}
        >
          <h2 className="text-2xl font-bold text-gray-900 mb-6 flex items-center gap-3">
            <FiCheck className="text-[#2563EB]" /> Responsibilities Dashboard
          </h2>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">
            {responsibilities.map((resp) => (
              <motion.div
                key={resp}
                variants={fadeUp}
                className={`flex items-center gap-3 border rounded-2xl p-4 transition-colors cursor-default ${resp.includes('Kill Switch') ? 'bg-amber-50 border-amber-300 hover:border-amber-400' : 'bg-[#F8FAFC] border-gray-200 hover:border-[#2563EB]/30'}`}
              >
                <div className={`w-8 h-8 rounded-lg flex items-center justify-center flex-shrink-0 ${resp.includes('Kill Switch') ? 'bg-amber-200' : 'bg-green-100'}`}>
                  {resp.includes('Kill Switch') ? <FiAlertTriangle className="text-amber-700" /> : <FiCheck className="text-green-600" />}
                </div>
                <span className="text-sm font-medium text-gray-700">{resp}</span>
              </motion.div>
            ))}
          </div>
        </motion.section>

        {/* SECTION 7: Inputs & Outputs */}
        <motion.section
          initial="hidden"
          whileInView="visible"
          viewport={{ once: true, margin: '-100px' }}
          variants={fadeUp}
          className="bg-[#F8FAFC] rounded-2xl p-6 md:p-8"
        >
          <h2 className="text-2xl font-bold text-gray-900 mb-8 flex items-center gap-3">
            <FiArrowRight className="text-[#2563EB]" /> Inputs & Outputs
          </h2>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6 items-start">
            <motion.div
              initial={{ opacity: 0, x: -30 }}
              whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: true }}
              className="bg-blue-50 border border-blue-200 rounded-2xl p-5"
            >
              <h3 className="font-semibold text-[#2563EB] mb-3 flex items-center gap-2"><FiArrowRight className="rotate-180" /> INPUTS</h3>
              <ul className="space-y-2 text-sm text-gray-700">
                <li className="flex items-center gap-2"><span className="w-2 h-2 rounded-full bg-[#2563EB]" /> Strategy Signals</li>
                <li className="flex items-center gap-2"><span className="w-2 h-2 rounded-full bg-[#2563EB]" /> Order Requests</li>
                <li className="flex items-center gap-2"><span className="w-2 h-2 rounded-full bg-[#2563EB]" /> Configurations</li>
                <li className="flex items-center gap-2"><span className="w-2 h-2 rounded-full bg-[#2563EB]" /> Risk Parameters</li>
                <li className="flex items-center gap-2"><span className="w-2 h-2 rounded-full bg-[#2563EB]" /> Manual Overrides</li>
              </ul>
            </motion.div>

            <motion.div
              initial={{ opacity: 0, scale: 0.8 }}
              whileInView={{ opacity: 1, scale: 1 }}
              viewport={{ once: true }}
              className="flex flex-col items-center justify-center py-6"
            >
              <div className="w-16 h-16 rounded-full bg-[#2563EB]/10 flex items-center justify-center mb-2">
                <FiPlay className="text-2xl text-[#2563EB]" />
              </div>
              <span className="text-sm font-semibold text-[#2563EB]">EXECUTION</span>
              <span className="text-xs text-gray-400 mt-1">8ms Latency</span>
            </motion.div>

            <motion.div
              initial={{ opacity: 0, x: 30 }}
              whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: true }}
              className="bg-green-50 border border-green-200 rounded-2xl p-5"
            >
              <h3 className="font-semibold text-green-700 mb-3 flex items-center gap-2"><FiArrowRight /> OUTPUTS</h3>
              <ul className="space-y-2 text-sm text-gray-700">
                <li className="flex items-center gap-2"><span className="w-2 h-2 rounded-full bg-green-600" /> Broker Orders</li>
                <li className="flex items-center gap-2"><span className="w-2 h-2 rounded-full bg-green-600" /> Trade Confirmations</li>
                <li className="flex items-center gap-2"><span className="w-2 h-2 rounded-full bg-green-600" /> Position Updates</li>
                <li className="flex items-center gap-2"><span className="w-2 h-2 rounded-full bg-green-600" /> Execution Reports</li>
                <li className="flex items-center gap-2"><span className="w-2 h-2 rounded-full bg-green-600" /> Audit Logs</li>
              </ul>
            </motion.div>
          </div>
        </motion.section>

        {/* SECTION 8: Performance Dashboard */}
        <motion.section
          initial="hidden"
          whileInView="visible"
          viewport={{ once: true, margin: '-100px' }}
          variants={stagger}
        >
          <h2 className="text-2xl font-bold text-gray-900 mb-6 flex items-center gap-3">
            <FiBarChart2 className="text-[#2563EB]" /> Performance Dashboard
          </h2>
          <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-4">
            {[
              { label: 'Orders/sec', value: 500, suffix: '', icon: FiZap, color: 'bg-amber-50 text-amber-700 border-amber-200' },
              { label: 'Latency', value: 8, suffix: 'ms', icon: FiClock, color: 'bg-green-50 text-green-700 border-green-200' },
              { label: 'Brokers Connected', value: 3, suffix: '', icon: FiWifi, color: 'bg-blue-50 text-blue-700 border-blue-200' },
              { label: 'Active Strategies', value: 42, suffix: '', icon: FiTarget, color: 'bg-purple-50 text-purple-700 border-purple-200' },
              { label: 'Order Success', value: 99.97, suffix: '%', icon: FiCheck, color: 'bg-emerald-50 text-emerald-700 border-emerald-200' },
              { label: 'Avg Fill Time', value: 120, suffix: 'ms', icon: FiRefreshCw, color: 'bg-cyan-50 text-cyan-700 border-cyan-200' },
              { label: 'Queue Depth', value: 18, suffix: '', icon: FiLayers, color: 'bg-indigo-50 text-indigo-700 border-indigo-200' },
              { label: 'CPU', value: 34, suffix: '%', icon: FiCpu, color: 'bg-rose-50 text-rose-700 border-rose-200' },
            ].map((stat) => (
              <motion.div
                key={stat.label}
                initial="rest"
                whileHover="hover"
                variants={cardHover}
                className={`${stat.color} border rounded-2xl p-5`}
              >
                <div className="flex items-center gap-2 mb-2">
                  <stat.icon className="opacity-70" />
                  <span className="text-xs font-medium uppercase tracking-wider opacity-70">{stat.label}</span>
                </div>
                <span className="text-2xl font-bold">
                  <AnimatedCounter value={stat.value} suffix={stat.suffix} />
                </span>
              </motion.div>
            ))}
          </div>
        </motion.section>

        {/* SECTION 9: Health Dashboard */}
        <motion.section
          initial="hidden"
          whileInView="visible"
          viewport={{ once: true, margin: '-100px' }}
          variants={fadeUp}
          className="bg-[#F8FAFC] rounded-2xl p-6 md:p-8"
        >
          <h2 className="text-2xl font-bold text-gray-900 mb-6 flex items-center gap-3">
            <FiActivity className="text-[#2563EB]" /> Health Dashboard
          </h2>
          <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-5 gap-4">
            {healthItems.map((item) => (
              <motion.div
                key={item.label}
                whileHover={{ scale: 1.03 }}
                className="bg-white border border-gray-200 rounded-2xl p-4 flex items-center gap-3"
              >
                <span className={`w-3 h-3 rounded-full ${item.color} flex-shrink-0 ${item.label === 'Kill Switch' ? 'animate-pulse' : ''}`} />
                <div>
                  <p className="text-xs text-gray-400 font-medium">{item.label}</p>
                  <p className="text-sm font-semibold text-gray-800">{item.status}</p>
                </div>
              </motion.div>
            ))}
          </div>
        </motion.section>

        {/* SECTION 10: Component Explorer */}
        <motion.section
          initial="hidden"
          whileInView="visible"
          viewport={{ once: true, margin: '-100px' }}
          variants={fadeUp}
        >
          <h2 className="text-2xl font-bold text-gray-900 mb-6 flex items-center gap-3">
            <FiBox className="text-[#2563EB]" /> Component Explorer
          </h2>
          <div className="space-y-2">
            {components.map((comp) => (
              <motion.div
                key={comp.name}
                whileHover={{ scale: 1.005 }}
                className={`bg-white border rounded-2xl overflow-hidden transition-colors ${expandedComponent === comp.name ? 'border-[#2563EB] shadow-lg shadow-blue-100' : 'border-gray-200'}`}
              >
                <button
                  onClick={() => setExpandedComponent(expandedComponent === comp.name ? null : comp.name)}
                  className="w-full flex items-center justify-between p-4 text-left"
                >
                  <span className="font-semibold text-gray-800">{comp.name}</span>
                  <motion.span
                    animate={{ rotate: expandedComponent === comp.name ? 180 : 0 }}
                    className="text-gray-400"
                  >
                    <FiChevronDown />
                  </motion.span>
                </button>
                <AnimatePresence>
                  {expandedComponent === comp.name && (
                    <motion.div
                      initial={{ height: 0, opacity: 0 }}
                      animate={{ height: 'auto', opacity: 1 }}
                      exit={{ height: 0, opacity: 0 }}
                      transition={{ duration: 0.3 }}
                      className="overflow-hidden"
                    >
                      <div className="px-4 pb-4 text-sm text-gray-600 border-t border-gray-100 pt-3">
                        {comp.desc}
                      </div>
                    </motion.div>
                  )}
                </AnimatePresence>
              </motion.div>
            ))}
          </div>
        </motion.section>

        {/* SECTION 11: Dependency Explorer */}
        <motion.section
          initial="hidden"
          whileInView="visible"
          viewport={{ once: true, margin: '-100px' }}
          variants={fadeUp}
          className="bg-[#F8FAFC] rounded-2xl p-6 md:p-8"
        >
          <h2 className="text-2xl font-bold text-gray-900 mb-6 flex items-center gap-3">
            <FiGitBranch className="text-[#2563EB]" /> Dependency Explorer
          </h2>
          <div className="space-y-3">
            {dependencies.map((dep, i) => (
              <motion.div
                key={dep.name}
                initial={{ opacity: 0, x: -20 }}
                whileInView={{ opacity: 1, x: 0 }}
                viewport={{ once: true }}
                transition={{ delay: i * 0.08 }}
                className="bg-white border border-gray-200 rounded-2xl p-4 flex items-center gap-4"
              >
                <div className="w-10 h-10 rounded-xl bg-blue-100 flex items-center justify-center flex-shrink-0">
                  <span className="text-[#2563EB] font-bold text-sm">{i + 1}</span>
                </div>
                <div className="flex-1">
                  <p className="font-semibold text-gray-800">{dep.name}</p>
                  <p className="text-xs text-gray-400 mt-0.5">{dep.role}</p>
                </div>
                <FiArrowRight className="text-gray-300 flex-shrink-0" />
              </motion.div>
            ))}
          </div>
        </motion.section>

        {/* SECTION 12: Kill Switch Section */}
        <motion.section
          initial="hidden"
          whileInView="visible"
          viewport={{ once: true, margin: '-100px' }}
          variants={fadeUp}
          className="bg-gradient-to-r from-red-50 to-amber-50 border border-red-200 rounded-2xl p-6 md:p-8"
        >
          <div className="flex items-start gap-4 mb-4">
            <div className="w-14 h-14 rounded-2xl bg-red-100 flex items-center justify-center flex-shrink-0">
              <FiAlertTriangle className="text-2xl text-red-600" />
            </div>
            <div>
              <h2 className="text-2xl font-bold text-gray-900">Three-Layer Emergency Protection</h2>
              <p className="text-lg font-semibold text-red-700 mt-1">Layer 3 — Kill Switch (1.50% Drawdown)</p>
            </div>
          </div>
          <div className="space-y-3 text-gray-700 leading-relaxed">
            <p>
              <strong className="text-red-800">Vega hosts Layer 3 of the ecosystem&apos;s three-layer kill switch architecture</strong> — 
              the final execution safeguard that prevents catastrophic losses in extreme market conditions.
            </p>
            <p>
              <strong>Layer 1 (Kavach):</strong> Risk management engine monitors strategy-level exposure. &mdash;{' '}
              <strong>Layer 2 (Rakshak):</strong> System-level protections monitor engine health and connectivity. &mdash;{' '}
              <strong>Layer 3 (Vega):</strong> <span className="text-red-700 font-semibold">1.50% drawdown trigger</span> — 
              if total portfolio drawdown breaches 1.50% intraday, Vega immediately suspends all new order placements while 
              allowing existing positions to be closed. This is the absolute last line of defense before the broker&apos;s own risk limits.
            </p>
            <div className="bg-white border border-red-200 rounded-xl p-4 mt-4">
              <div className="flex items-center justify-between mb-2">
                <span className="text-sm font-medium text-gray-600">Current Drawdown</span>
                <span className="text-sm font-bold text-green-600">0.34%</span>
              </div>
              <div className="w-full bg-gray-200 rounded-full h-2.5">
                <div className="bg-green-500 h-2.5 rounded-full" style={{ width: '22.7%' }} />
              </div>
              <div className="flex items-center justify-between mt-1">
                <span className="text-xs text-gray-400">0%</span>
                <span className="text-xs text-red-500 font-semibold">Threshold: 1.50%</span>
              </div>
              <div className="flex items-center gap-2 mt-3 p-2 bg-green-50 rounded-lg">
                <FiCheck className="text-green-600 flex-shrink-0" />
                <span className="text-sm text-green-700 font-medium">Kill switch armed and operational — 1.16% remaining before trigger</span>
              </div>
            </div>
          </div>
        </motion.section>

        {/* SECTION 13: AI Explanation */}
        <motion.section
          initial="hidden"
          whileInView="visible"
          viewport={{ once: true, margin: '-100px' }}
          variants={fadeUp}
          className="bg-[#F8FAFC] rounded-2xl p-6 md:p-8"
        >
          <h2 className="text-2xl font-bold text-gray-900 mb-6 flex items-center gap-3">
            <FiCpu className="text-[#2563EB]" /> AI Explanation
          </h2>
          <div className="flex flex-wrap gap-3 mb-6">
            {[
              { key: 'simple', label: 'Explain Simply', icon: FiInfo },
              { key: 'technical', label: 'Technical Deep Dive', icon: FiCode },
              { key: 'architecture', label: 'Architecture View', icon: FiLayers },
            ].map((btn) => (
              <motion.button
                key={btn.key}
                whileHover={{ scale: 1.05 }}
                whileTap={{ scale: 0.95 }}
                onClick={() => setAiView(aiView === btn.key ? null : btn.key)}
                className={`flex items-center gap-2 px-5 py-2.5 rounded-xl text-sm font-semibold transition-colors ${aiView === btn.key ? 'bg-[#2563EB] text-white shadow-lg shadow-blue-200' : 'bg-white border border-gray-200 text-gray-700 hover:border-[#2563EB]/40'}`}
              >
                <btn.icon /> {btn.label}
              </motion.button>
            ))}
          </div>
          <AnimatePresence>
            {aiView && (
              <motion.div
                initial={{ height: 0, opacity: 0 }}
                animate={{ height: 'auto', opacity: 1 }}
                exit={{ height: 0, opacity: 0 }}
                transition={{ duration: 0.4 }}
                className="overflow-hidden"
              >
                <div className="bg-white border border-[#2563EB]/20 rounded-2xl p-6 text-gray-700 leading-relaxed">
                  {aiExplanations[aiView]}
                </div>
              </motion.div>
            )}
          </AnimatePresence>
        </motion.section>

        <div className="h-8" />
      </div>
    </div>
  );
}
